sudo: false
language: go
go: 1.4
script:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/cloudflare/redoctober
  - go test github.com/cloudflare/redoctober...
  - go vet github.com/cloudflare/redoctober...
notifications:
  email:
    recipients:
      - nick@cloudflare.com
      - kyle@cloudflare.com
      - zi@cloudflare.com
    on_success: never
    on_failure: change
